force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizzes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Threshold__c.field-meta.xml
<CustomField>
    <fullName>Threshold__c</fullName>
    <label>Threshold</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz_Answer</label>
    <nameField>
        <label>Quiz_Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz_Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Answer__c/fields/Quiz_Question__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Question__c</fullName>
    <label>Quiz_Question</label>
    <referenceTo>Quiz_Question__c</referenceTo>
    <relationshipLabel>Quiz_Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/Quiz_Question__c.object-meta.xml
<CustomObject>
    <label>Quiz_Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quiz_Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz_Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Question__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quiz_Question__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Quiz_Questions</relationshipLabel>
    <relationshipName>Quiz_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuizDataFactory.cls
@isTest
public with sharing class QuizDataFactory {

    // create 1 quiz, with 1 question and 'ansNum' answers,
    // the latter of which the first 'ansCorrect' are right.
    public static Qna getQnaOfSampleQuiz(Integer ansNum, Integer ansCorrect){
        Qna qna = new Qna();
        qna.quizId = QuizDataFactory.createQuiz();
        qna.questionId = QuizDataFactory.createQuestionByQuizId(qna.quizId);
        qna.answerIds = QuizDataFactory.createAnswersByQuestionId(qna.questionId, ansNum, ansCorrect);

        return qna;
    }
    
    public static String createQuiz(){
        String quizName = 'Test Quiz';
        Quiz__c quiz = new Quiz__c(Name = quizName, Threshold__c = 0);
        insert quiz;
        return [SELECT Id FROM Quiz__c WHERE Name = :quizName LIMIT 1].Id;
    }

    public static String createQuestionByQuizId(String quizId){
        String qDescr = 'Test Question';
        Quiz_Question__c question = new Quiz_Question__c(Description__c = qDescr, Quiz__c = quizId);
        insert question;
        return [SELECT Id, Description__c FROM Quiz_Question__c WHERE Description__c = :qDescr LIMIT 1].Id;
    }

    public static List<String> createAnswersByQuestionId(String qId, Integer ansNum, Integer ansCorrect){
        // input safety
        if(ansCorrect > ansNum){
            ansNum = ansCorrect;
        }
        
        List<Quiz_Answer__c> answers = new List<Quiz_Answer__c>();
        for(Integer i = 0; i < ansNum; i++){
            Boolean correct = (i < ansCorrect);
            answers.add(new Quiz_Answer__c(Quiz_Question__c = qId, Description__c = 'Answer ' + i, isCorrect__c = correct));
        }
        insert answers;

        List<String> aIds = new List<String>();
        for(Quiz_Answer__c ans : [SELECT Id FROM Quiz_Answer__c WHERE Quiz_Question__c = :qId]){
            aIds.add(Id.valueOf(ans.Id));
        }

        return aIds;
    }

    // wrapping class
    public class Qna {
        public String quizId;
        public String questionId;
        public List<String> answerIds;
    }
}